default: &default
  brand:
    name: 'SiSINTA'
    url: 'http://sisinta.inta.gob.ar'
    contact: 'sisinta at inta.gob.ar'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  brand:
    name: <%= ENV['SISINTA_BRAND_NAME'] %>
    url: <%= ENV['SISINTA_BRAND_URL'] %>
    contact: <%= ENV['SISINTA_BRAND_CONTACT'] %>
